resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 2m
  #webhook_token: ((webhook-token))
  source:
    repository: prashant887/concourse-pr-event
    access_token: ((github-access-token))
    #branch: master

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: pull-request
      run:
        path: echo
        args: [hello]