resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: ndrjng/concourse-github-pr-comment-resource
      #tag: latest

resources:
- name: pull-request
  type: pull-request
  check_every: 2m
  #webhook_token: ((webhook-token))
  source:
    repository: prashant887/concourse-pr-event
    access_token: ((github-access-token))
    #branch: master

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: pull-request
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            cd pull-request
            git log --graph --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" > log.txt
            cat log.txt
