resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 2m
  source:
    repository: prashant887/concourse-pr-event
    access_token: ((github-access-token))

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: concourse-pr-event
      status: pending
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: concourse-pr-event
      params:
        branch: master
      run:
        dir: concourse-pr-event
        path: sh
        args:
          - -exec
          - |
            sleep 60
  on_success:
    do:
      - put: pull-request
        params:
          path: concourse-pr-event
          status: success
  on_failure:
    do:
      - put: pull-request
        params:
          path: concourse-pr-event
          status: failure